### ISSUE TITLE
Add a list of all publications that use Mimi.jl

### ISSUE THREAD

**Issue by davidanthoff** [mimiframework/mimiframework.github.io#12]
We should add a section that just lists all the publications that use Mimi.jl. For starters, here are the ones I'm a co-author on:
```
“Health Impacts of Climate Change as Contained in Economic Models Estimating the Social Cost of Carbon Dioxide,” with Kevin Cromar, Peter Howard and Valeri Vasquez, GeoHealth, forthcoming

“The importance of health co-benefits under different climate policy cooperation frameworks,” with Noah Scovronick, Francis Dennig, Frank Errickson, Maddalena Ferranna, Wei Peng, Dean Spears, Fabian Wagner and Mark Budolfson, Environmental Research Letters, 2021, 16(5).

“Equity is more important for the social cost of methane than climate uncertainty,” with Frank C. Errickson, Klaus Keller, William D. Collins and Vivek Srikrishnan, Nature, 2021, 592: 564–570.

“Inequality and the Social Cost of Carbon,” with Johannes Emmerling, Journal of the Association of Environmental and Resource Economists, 2019, 6(2): 29-59.

“Mimi-PAGE, an open-source implementation of the PAGE09 integrated assessment model,” with Frances Moore, James Rising, Niklas Lollo, Cecilia Springer, Valeri Vasquez, Alex Dolginow and Chris Hope, Scientific Data, 2018, 5: 180187.

“Priority for the worse-off and the social cost of carbon,” with Matthew Adler, Valentina Bosetti, Greg Garner, Klaus Keller and Nicolas Treich, Nature Climate Change, 2017, 7(6): 443-449.
```
That list is not well formatted because I'm never listed as an author and the author order list is off :) So we'll need to adjust that before we add it to the web page.

@frankerrickson sent me this list of his additional papers:
```
Errickson, F.C., Kuruc, K., and McFadden, J. (2021). Animal-based foods have high social and climate costs." Nature Food 2, 274-281. doi:10.1038/s43016-021-00265-1

Scovronick, N., Budolfson, M.B., Dennig, F., Errickson, F.C., Fleurbaey, M., Peng, W., Socolow, R.H., Spears, D., Wagner, F. (2019). The impact of human health co-benefits on evaluations of global climate policy." Nature Communications 10, 2095. doi:10.1038/s41467-019-09499-x
```

@fdennig: do you have other papers that are published or accepted that use Mimi.jl? If so, we should add those here as well! @jrising anything from your end? If anyone can think of others, please also ping them here.

@lrennels and you as the only person who understands this web page code here, could you add this? :) Thanks!

**Comment by lrennels** [comment]
Sure I can do this now, I'm thinking we would want this to be a separate menu item on the left hand side?  Coincidentally I haven't figured out how to add one but it's time I learned.

**Comment by lrennels** [comment]
https://www.mimiframework.org/menu5/

keep posting things here and let mea now if there are any typos, I pulled the doi numbers and used APA formatting

**Comment by jrising** [comment]
Here are a couple from me:

Rising, J. & Devineni, N. (2020). Crop switching reduces agricultural losses from climate change in the United States by half under RCP 8.5. Nature Communications.

Rising, J. (2020). Decision-making and integrated assessment models of the water-energy-food nexus. Water Security.
